name: flarum

services:
  db:
    image: mariadb:10
    container_name: flarum_db
    command:
      - "mysqld"
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
    volumes:
      - "./db:/var/lib/mysql"
    environment:
      - "TZ"
      - "MARIADB_RANDOM_ROOT_PASSWORD=yes"
      - "MYSQL_DATABASE"
      - "MYSQL_USER"
      - "MYSQL_PASSWORD"
    restart: always

  msmtpd:
    image: crazymax/msmtpd:latest
    container_name: flarum_msmtpd
    env_file:
      - "./msmtpd.env"
    environment:
      - "TZ"
    restart: always

  flarum:
    image: crazymax/flarum:latest
    container_name: flarum
    ports:
      - target: 8000
        published: 8000
        protocol: tcp
    depends_on:
      - db
      - msmtpd
    volumes:
      - "./data:/data"
    environment:
      - "TZ"
      - "PUID"
      - "PGID"
      - "DB_HOST=db"
      - "DB_NAME=${MYSQL_DATABASE}"
      - "DB_USER=${MYSQL_USER}"
      - "DB_PASSWORD=${MYSQL_PASSWORD}"
    env_file:
      - "./flarum.env"
    restart: always
